import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
const databaseUrl = process.env.TEST_DATABASE_URL ?? 'postgres://lab:lab_local@127.0.0.1:55433/lab_test';
if (!new URL(databaseUrl).pathname.endsWith('_test')) throw new Error('Dedicated test database required');
const pool = new Pool({ connectionString: databaseUrl });
test.beforeAll(async () => { await migrate(drizzle(pool), { migrationsFolder: './database/migrations' }); });
test.beforeEach(async () => { await pool.query('DELETE FROM activities'); await pool.query('DELETE FROM ideas'); await pool.query('DELETE FROM rate_limits'); });
test.afterAll(async () => { await pool.end(); });
test('Owner prepares an Event from an Idea; Visitors see tentative conditions without private details', async ({ page, browser, request }) => {
  const email = `project-${randomUUID()}@gso.schule.koeln`;
  await page.goto('/login');
  await page.getByLabel('Name', { exact: true }).fill('Private owner');
  await page.getByLabel('Schul-E-Mail').fill(email);
  await page.getByRole('button', { name: 'Login-Link senden' }).click();
  await expect(page.getByRole('status')).toContainText('Postfach');
  const box = await request.get(`http://127.0.0.1:8025/api/v1/search?query=${encodeURIComponent(`to:${email}`)}`).then(r => r.json());
  const mail = await request.get(`http://127.0.0.1:8025/api/v1/message/${box.messages[0].ID}`).then(r => r.json());
  await page.goto(mail.Text.match(/https?:\/\/\S+/)[0]);
  const idea = await pool.query("INSERT INTO ideas(title,description) VALUES('Build a homelab','An idea without obligation.') RETURNING id");
  await page.goto(`/ideas/${idea.rows[0].id}`);
  await page.getByRole('link', { name: 'Event daraus erstellen' }).click();
  await page.getByLabel('Titel', { exact: true }).fill('Docker gemeinsam lernen');
  await page.getByLabel('Beschreibung', { exact: true }).fill('Container bauen und ausprobieren.');
  await page.getByLabel('Kategorie', { exact: true }).selectOption('WORKSHOP');
  await page.getByText('Nur für Members', { exact: true }).click();
  await page.getByLabel('Interne Hinweise', { exact: true }).fill('Private entrance instructions');
  await page.getByRole('button', { name: 'Event erstellen', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Docker gemeinsam lernen' })).toBeVisible();
  await expect(page.getByText('Termin noch offen', { exact: true })).toBeVisible();
  await expect(page.getByText('Private owner', { exact: true })).toBeVisible();
  const url = page.url();
  const visitor = await browser.newContext({ viewport: { width: 390, height: 844 } });
  try {
    const publicPage = await visitor.newPage();
    await publicPage.goto(url);
    await expect(publicPage.getByText('GSO', { exact: true })).toBeVisible();
    await expect(publicPage.locator('main')).not.toContainText('A103');
    await expect(publicPage.locator('main')).not.toContainText('Private owner');
    await expect(publicPage.locator('main')).not.toContainText('Private entrance instructions');
    await page.getByRole('link', { name: 'Event bearbeiten' }).click();
    await page.getByLabel('Geplantes Datum', { exact: true }).fill('2026-11-28');
    await page.getByLabel('Beginn', { exact: true }).fill('16:00');
    await page.getByLabel('Ende', { exact: true }).fill('18:00');
    await page.locator('select[name="placeType"]').selectOption('OTHER');
    await page.getByLabel('Allgemeiner Ort', { exact: true }).fill('Köln');
    await page.getByRole('button', { name: 'Änderungen speichern' }).click();
    await expect(page.getByText('16:00', { exact: false })).toBeVisible();
    await publicPage.reload();
    await publicPage.getByRole('button', { name: 'English' }).click();
    await expect(publicPage.getByText('Planned · not yet confirmed', { exact: true })).toBeVisible();
    await expect(publicPage.getByText('Köln', { exact: true })).toBeVisible();
    await expect(publicPage.getByRole('heading', { name: 'Docker gemeinsam lernen' })).toBeVisible();
    expect(await publicPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await publicPage.getByRole('link', { name: 'All events', exact: false }).click();
    await expect(publicPage.getByRole('heading', { name: 'Docker gemeinsam lernen' })).toBeVisible();
  } finally { await visitor.close(); }
});
