import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
const databaseUrl = process.env.TEST_DATABASE_URL ?? 'postgres://lab:lab_local@127.0.0.1:55433/lab_test';
if (!new URL(databaseUrl).pathname.endsWith('_test')) throw new Error('Dedicated test database required');
const pool = new Pool({ connectionString: databaseUrl });
test.beforeAll(async () => { await migrate(drizzle(pool), { migrationsFolder: './database/migrations' }); });
test.beforeEach(async () => { await pool.query('DELETE FROM activities'); await pool.query('DELETE FROM ideas'); await pool.query('DELETE FROM rate_limits'); });
test.afterAll(async () => { await pool.end(); });
test('Owner opens registration, Member joins, and a reschedule requires fresh confirmation', async ({ page, browser, request }) => {
  const email = `project-${randomUUID()}@gso.schule.koeln`;
  await page.goto('/login');
  await page.getByLabel('Name', { exact: true }).fill('Private owner');
  await page.getByLabel('Schul-E-Mail').fill(email);
  await page.getByRole('button', { name: 'Login-Link senden' }).click();
  await expect(page.getByRole('status')).toContainText('Postfach');
  const box = await request.get(`http://127.0.0.1:8025/api/v1/search?query=${encodeURIComponent(`to:${email}`)}`).then(r => r.json());
  const mail = await request.get(`http://127.0.0.1:8025/api/v1/message/${box.messages[0].ID}`).then(r => r.json());
  await page.goto(mail.Text.match(/https?:\/\/\S+/)[0]);
  const created=await page.request.post('/api/events',{headers:{origin:'http://127.0.0.1:5173'},data:{title:'Going workshop',description:'Learn together',category:'WORKSHOP',plannedDate:'2026-11-28',startTime:'16:00',endTime:'18:00',generalLocation:'Online'}});
  const id=(await created.json()).event.id;
  await page.goto(`/events/${id}`);
  await page.getByRole('button',{name:'Anmeldung öffnen',exact:true}).click();
  await expect(page.getByText('Anmeldung offen',{exact:true}).first()).toBeVisible();
  await page.getByRole('button',{name:'Ich bin dabei',exact:true}).click();
  await expect(page.getByText('1 angemeldet',{exact:true})).toBeVisible();
  const visitor=await browser.newContext({viewport:{width:390,height:844}});
  try {
    const publicPage=await visitor.newPage();await publicPage.goto(`/events/${id}`);
    await expect(publicPage.getByText('1 angemeldet',{exact:true})).toBeVisible();
    await expect(publicPage.locator('main')).not.toContainText('Private owner');
    await page.getByRole('link',{name:'Event bearbeiten',exact:true}).click();
    await expect(page.getByText('Änderst du Datum oder Uhrzeit, werden Anmeldungen zu Interesse. Öffne die Anmeldung danach erneut und informiere alle über Discord.',{exact:true})).toBeVisible();
    await page.getByLabel('Geplantes Datum',{exact:true}).fill('2026-11-29');
    await page.getByRole('button',{name:'Änderungen speichern',exact:true}).click();
    await expect(page.getByText('0 angemeldet',{exact:true})).toBeVisible();
    await expect(page.getByText('1 interessiert',{exact:true})).toBeVisible();
    await expect(page.getByRole('button',{name:'Ich bin dabei',exact:true})).toHaveCount(0);
    await page.getByRole('button',{name:'English'}).click();
    await page.getByRole('button',{name:'Open registration',exact:true}).click();
    await page.getByRole('button',{name:'I’m going',exact:true}).click();
    await expect(page.getByText('1 going',{exact:true})).toBeVisible();
    await page.getByRole('button',{name:'Withdraw registration',exact:true}).click();
    await expect(page.getByText('0 going',{exact:true})).toBeVisible();
    await page.getByLabel('Room wishes',{exact:true}).fill('Need a classroom now');
    await page.getByRole('button',{name:'Request room',exact:true}).click();
    await expect(page.getByText('Waiting for Ops',{exact:true})).toBeVisible();
    await expect(page.getByText('Registration open',{exact:true})).toHaveCount(0);
    await expect(page.getByRole('button',{name:'I’m going',exact:true})).toHaveCount(0);
    await expect(page.getByRole('button',{name:'Open registration',exact:true})).toBeDisabled();
    await publicPage.reload();expect(await publicPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  } finally {await visitor.close();}
});
