import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
const databaseUrl = process.env.TEST_DATABASE_URL ?? 'postgres://lab:lab_local@127.0.0.1:55433/lab_test';
if (!new URL(databaseUrl).pathname.endsWith('_test')) throw new Error('Dedicated test database required');
const pool = new Pool({ connectionString: databaseUrl });
test.beforeAll(async () => { await migrate(drizzle(pool), { migrationsFolder: './database/migrations' }); });
test.beforeEach(async () => { await pool.query('DELETE FROM activities'); await pool.query('DELETE FROM ideas'); await pool.query('DELETE FROM rate_limits'); });
test.afterAll(async () => { await pool.end(); });
test('Owner confirms remaining work before cancellation; archived Project stays readable in DE and EN',async({page})=>{
 const email=`close-${randomUUID()}@gso.schule.koeln`;
 await page.goto('/login');await page.getByLabel('Name',{exact:true}).fill('Closing owner');await page.getByLabel('Schul-E-Mail').fill(email);
 await page.getByRole('button',{name:'Login-Link senden'}).click();await expect(page.getByRole('status')).toContainText('Postfach');
 const box=await page.request.get(`http://127.0.0.1:8025/api/v1/search?query=${encodeURIComponent(`to:${email}`)}`).then(r=>r.json());
 const mail=await page.request.get(`http://127.0.0.1:8025/api/v1/message/${box.messages[0].ID}`).then(r=>r.json());await page.goto(mail.Text.match(/https?:\/\/\S+/)[0]);
 const result=await page.request.post('/api/projects',{headers:{origin:'http://127.0.0.1:5173'},data:{title:'Archived build',goal:'Keep results',description:'Our findings',materials:'Demo notes'}});
 const id=(await result.json()).project.id;
 await page.request.post(`/api/activities/${id}/tasks`,{headers:{origin:'http://127.0.0.1:5173'},data:{title:'Remaining work'}});
 await page.goto(`/projects/${id}`);
 await page.getByText('Activity abschließen',{exact:true}).click();await page.getByRole('button',{name:'Activity absagen',exact:true}).click();
 await expect(page.getByText('1 offene oder laufende Aufgaben werden abgesagt.',{exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Absage bestätigen',exact:true})).toBeDisabled();
 await page.getByLabel('Alle verbleibenden Aufgaben absagen',{exact:true}).check();await page.getByRole('button',{name:'Absage bestätigen',exact:true}).click();
 await expect(page.getByRole('button',{name:'Aufgabe übernehmen',exact:true})).toHaveCount(0);
 await expect(page.getByRole('heading',{name:'Archived build',exact:true})).toBeVisible();await expect(page.getByText('Demo notes',{exact:true})).toBeVisible();
 await page.goto('/projects');await expect(page.getByRole('heading',{name:'Archived build',exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Vergangene',exact:true}).click();await page.getByRole('heading',{name:'Archived build',exact:true}).click();
 await page.getByRole('button',{name:'English'}).click();await expect(page.getByText('Cancelled',{exact:true}).first()).toBeVisible();
 await expect(page.getByRole('button',{name:'Start work',exact:true})).toHaveCount(0);await expect(page.getByText('Transfer ownership',{exact:true})).toHaveCount(0);
});
