import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
const databaseUrl = process.env.TEST_DATABASE_URL ?? 'postgres://lab:lab_local@127.0.0.1:55433/lab_test';
if (!new URL(databaseUrl).pathname.endsWith('_test')) throw new Error('Dedicated test database required');
const pool = new Pool({ connectionString: databaseUrl });
test.beforeAll(async () => { await migrate(drizzle(pool), { migrationsFolder: './database/migrations' }); });
test.beforeEach(async () => { await pool.query('DELETE FROM activities'); await pool.query('DELETE FROM ideas'); await pool.query('DELETE FROM rate_limits'); });
test.afterAll(async () => { await pool.end(); });
test('Member joins and leaves a Project; private team identities and owner responsibilities stay protected', async ({ page, browser, request }) => {
  const email = `project-${randomUUID()}@gso.schule.koeln`;
  await page.goto('/login');
  await page.getByLabel('Name', { exact: true }).fill('Private owner');
  await page.getByLabel('Schul-E-Mail').fill(email);
  await page.getByRole('button', { name: 'Login-Link senden' }).click();
  await expect(page.getByRole('status')).toContainText('Postfach');
  const box = await request.get(`http://127.0.0.1:8025/api/v1/search?query=${encodeURIComponent(`to:${email}`)}`).then(r => r.json());
  const mail = await request.get(`http://127.0.0.1:8025/api/v1/message/${box.messages[0].ID}`).then(r => r.json());
  await page.goto(mail.Text.match(/https?:\/\/\S+/)[0]);
  const ownerId = randomUUID();
  await pool.query("INSERT INTO users(id,name,email,email_verified) VALUES($1,'Project owner',$2,true)",[ownerId,`owner-${ownerId}@gso.schule.koeln`]);
  const activity = await pool.query("INSERT INTO activities(type,title,description,owner_id) VALUES('PROJECT','Team Lab','Build together',$1) RETURNING id",[ownerId]);
  const id = activity.rows[0].id;
  await pool.query("INSERT INTO project_details(activity_id,goal) VALUES($1,'Learn together')",[id]);
  await page.goto(`/projects/${id}`);
  await expect(page.getByText('0 im Team', {exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Projekt beitreten',exact:true}).click();
  await expect(page.getByText('1 im Team',{exact:true})).toBeVisible();
  await expect(page.getByRole('region',{name:'Team',exact:true}).getByText('Private owner',{exact:true})).toBeVisible();
  await page.reload();
  await expect(page.getByRole('button',{name:'Team verlassen',exact:true})).toBeVisible();
  const visitor = await browser.newContext({viewport:{width:390,height:844}});
  try {
    const publicPage = await visitor.newPage();
    await publicPage.goto(`/projects/${id}`);
    await expect(publicPage.getByText('1 im Team',{exact:true})).toBeVisible();
    await expect(publicPage.locator('main')).not.toContainText('Private owner');
    await expect(publicPage.getByRole('button',{name:'Projekt beitreten',exact:true})).toHaveCount(0);
    await page.getByRole('button',{name:'English'}).click();
    await page.getByRole('button',{name:'Leave team',exact:true}).click();
    await expect(page.getByText('0 in the team',{exact:true})).toBeVisible();
    await page.getByRole('button',{name:'Join project',exact:true}).click();
    await expect(page.getByText('1 in the team',{exact:true})).toBeVisible();
    await pool.query('UPDATE activities SET owner_id=(SELECT id FROM users WHERE email=$2) WHERE id=$1',[id,email]);
    await page.reload();
    await expect(page.getByText('You own this project. Transfer responsibility before leaving.',{exact:true})).toBeVisible();
    await expect(page.getByRole('button',{name:'Leave team',exact:true})).toHaveCount(0);
    await page.setViewportSize({width:390,height:844});
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  } finally { await visitor.close(); }
});
