import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { Pool } from 'pg';
import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
const databaseUrl = process.env.TEST_DATABASE_URL ?? 'postgres://lab:lab_local@127.0.0.1:55433/lab_test';
if (!new URL(databaseUrl).pathname.endsWith('_test')) throw new Error('Dedicated test database required');
const pool = new Pool({ connectionString: databaseUrl });
const firstEmail = `ops-browser-${randomUUID()}@gso.schule.koeln`;
const secondId = randomUUID();
test.beforeAll(async () => {
  await migrate(drizzle(pool), { migrationsFolder: './database/migrations' });
  await pool.query('DELETE FROM rate_limits');
  await pool.query('DELETE FROM role_changes');
  await pool.query("UPDATE users SET role='MEMBER'");
  await pool.query("INSERT INTO users (id,name,email,email_verified) VALUES ($1,'Existing Ops',$2,true),($3,'New candidate',$4,true)", [randomUUID(), firstEmail, secondId, `candidate-${randomUUID()}@gso.schule.koeln`]);
  await promisify(execFile)(process.execPath, ['--import', 'tsx', 'apps/api/src/modules/ops/bootstrap.ts', '--email', firstEmail, '--confirmed-by', 'School sponsor', '--operator', 'Server admin'], { env: { ...process.env, DATABASE_URL: databaseUrl } });
});
test.afterAll(async () => { await pool.end(); });
test('Ops appoints a Member in the bilingual UI and sees the recorded change on mobile', async ({ page, request }) => {
  await page.goto('/login');
  await page.getByLabel('Name', { exact: true }).fill('Existing Ops');
  await page.getByLabel('Schul-E-Mail').fill(firstEmail);
  await page.getByRole('button', { name: 'Login-Link senden' }).click();
  await expect(page.getByRole('status')).toContainText('Postfach');
  const box = await request.get(`http://127.0.0.1:8025/api/v1/search?query=${encodeURIComponent(`to:${firstEmail}`)}`).then(r => r.json());
  const mail = await request.get(`http://127.0.0.1:8025/api/v1/message/${box.messages[0].ID}`).then(r => r.json());
  await page.goto(mail.Text.match(/https?:\/\/\S+/)[0]);
  await page.getByRole('link', { name: 'Ops verwalten' }).click();
  await expect(page.getByRole('heading', { name: 'Ops-Team' })).toBeVisible();
  await page.getByRole('button', { name: 'English' }).click();
  await page.getByLabel('Member', { exact: true }).selectOption(secondId);
  await page.getByRole('button', { name: 'Appoint Ops' }).click();
  await expect(page.getByRole('status')).toContainText('appointed');
  await page.reload();
  await expect(page.getByRole('list', { name: 'Ops team' })).toContainText('New candidate');
  await expect(page.getByRole('list', { name: 'Role history' })).toContainText('Existing Ops');
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
