import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
const databaseUrl = process.env.TEST_DATABASE_URL ?? 'postgres://lab:lab_local@127.0.0.1:55433/lab_test';
if (!new URL(databaseUrl).pathname.endsWith('_test')) throw new Error('Dedicated test database required');
const pool = new Pool({ connectionString: databaseUrl });
test.beforeAll(async () => { await migrate(drizzle(pool), { migrationsFolder: './database/migrations' }); });
test.beforeEach(async () => { await pool.query('DELETE FROM activities'); await pool.query('DELETE FROM ideas'); await pool.query('DELETE FROM rate_limits'); });
test.afterAll(async () => { await pool.end(); });
test('Owner creates from an Idea, adds materials to description and starts work while Visitors see only public information', async ({ page, browser, request }) => {
  const email = `project-${randomUUID()}@gso.schule.koeln`;
  await page.goto('/login');
  await page.getByLabel('Name', { exact: true }).fill('Private owner');
  await page.getByLabel('Schul-E-Mail').fill(email);
  await page.getByRole('button', { name: 'Login-Link senden' }).click();
  await expect(page.getByRole('status')).toContainText('Postfach');
  const box = await request.get(`http://127.0.0.1:8025/api/v1/search?query=${encodeURIComponent(`to:${email}`)}`).then(r => r.json());
  const mail = await request.get(`http://127.0.0.1:8025/api/v1/message/${box.messages[0].ID}`).then(r => r.json());
  await page.goto(mail.Text.match(/https?:\/\/\S+/)[0]);
  const idea = await pool.query("INSERT INTO ideas(title,description) VALUES('Build a homelab','An idea without obligation.') RETURNING id");
  await page.goto(`/ideas/${idea.rows[0].id}`);
  await page.getByRole('link', { name: 'Projekt daraus starten' }).click();
  await page.getByLabel('Titel', { exact: true }).fill('Unser Homelab');
  await page.getByLabel('Ziel', { exact: true }).fill('Ein gemeinsames Labor bauen');
  await page.getByLabel('Beschreibung', { exact: true }).fill('Gemeinsam lernen und bauen. Öffentliche Notizen');
  await page.getByText('Links und Tech Stack', { exact: true }).click();
  await page.getByLabel('Tech Stack', { exact: true }).fill('Linux, Docker');
  await page.getByLabel('Repository', { exact: true }).fill('https://github.com/example/homelab');
  await page.getByText('Nur für Members', { exact: true }).click();
  await page.getByLabel('Interne Hinweise', { exact: true }).fill('Private instructions');
  await page.getByLabel('Discord-Link', { exact: true }).fill('https://discord.gg/private-example');
  await page.getByRole('button', { name: 'Projekt erstellen' }).click();
  await expect(page.getByRole('heading', { name: 'Unser Homelab' })).toBeVisible();
  await expect(page.getByText('Private owner', { exact: true })).toBeVisible();
  await expect(page.getByText('In Vorbereitung', { exact: true })).toBeVisible();
  const url = page.url();
  const visitor = await browser.newContext({ viewport: { width: 390, height: 844 } });
  try {
    const publicPage = await visitor.newPage();
    await publicPage.goto(url);
    await expect(publicPage.getByRole('heading', { name: 'Unser Homelab' })).toBeVisible();
    await expect(publicPage.locator('main')).not.toContainText('Private owner');
    await expect(publicPage.locator('main')).not.toContainText('Private instructions');
    await expect(publicPage.getByRole('link', { name: 'Discord' })).toHaveCount(0);
    await page.getByRole('link', { name: 'Projekt bearbeiten' }).click();
    await page.getByLabel('Ziel', { exact: true }).fill('Ein besseres Labor bauen');
    await page.getByRole('button', { name: 'Änderungen speichern' }).click();
    await expect(page.getByText('Ein besseres Labor bauen')).toBeVisible();
    await page.getByRole('link', { name: 'Projekt bearbeiten' }).click();
    await page.getByRole('button', { name: 'Arbeit starten' }).click();
    await page.goto(url);
    await expect(page.getByText('In Arbeit', { exact: true })).toBeVisible();
    await publicPage.reload();
    await publicPage.getByRole('button', { name: 'English' }).click();
    await expect(publicPage.getByText('In progress', { exact: true })).toBeVisible();
    await expect(publicPage.getByText('Öffentliche Notizen')).toBeVisible();
    expect(await publicPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  } finally { await visitor.close(); }
});
