import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
const databaseUrl = process.env.TEST_DATABASE_URL ?? 'postgres://lab:lab_local@127.0.0.1:55433/lab_test';
if (!new URL(databaseUrl).pathname.endsWith('_test')) throw new Error('Dedicated test database required');
const pool = new Pool({ connectionString: databaseUrl });
test.beforeAll(async () => { await migrate(drizzle(pool), { migrationsFolder: './database/migrations' }); });
test.beforeEach(async () => { await pool.query('DELETE FROM activities'); await pool.query('DELETE FROM ideas'); await pool.query('DELETE FROM rate_limits'); });
test.afterAll(async () => { await pool.end(); });
test('Owner requests a room and sees an Ops alternative before final confirmation in DE and EN', async ({ page, browser, request }) => {
  const email = `project-${randomUUID()}@gso.schule.koeln`;
  await page.goto('/login');
  await page.getByLabel('Name', { exact: true }).fill('Private owner');
  await page.getByLabel('Schul-E-Mail').fill(email);
  await page.getByRole('button', { name: 'Login-Link senden' }).click();
  await expect(page.getByRole('status')).toContainText('Postfach');
  const box = await request.get(`http://127.0.0.1:8025/api/v1/search?query=${encodeURIComponent(`to:${email}`)}`).then(r => r.json());
  const mail = await request.get(`http://127.0.0.1:8025/api/v1/message/${box.messages[0].ID}`).then(r => r.json());
  await page.goto(mail.Text.match(/https?:\/\/\S+/)[0]);
  const response=await page.request.post('/api/events',{headers:{origin:new URL(page.url()).origin},data:{title:'Room workshop',description:'Prepare together',category:'WORKSHOP',placeType:'SCHOOL',plannedDate:'2026-11-28',startTime:'16:00',endTime:'18:00'}});
  const id=(await response.json()).event.id;
  await page.goto(`/events/${id}`);
  await expect(page.getByText('Wartet auf Ops',{exact:true})).toBeVisible();
  await pool.query("UPDATE users SET role='OPS' WHERE email=$1",[email]);
  await page.goto('/ops');
  await page.getByRole('link',{name:'Raumanfragen',exact:true}).click();
  const item=page.getByRole('article').filter({has:page.getByRole('heading',{name:'Room workshop',exact:true})});
  await item.getByLabel('Datum',{exact:true}).fill('2026-11-28');
  await item.getByLabel('Beginn',{exact:true}).fill('17:00');
  await item.getByLabel('Ende',{exact:true}).fill('19:00');
  await item.getByLabel('Raum',{exact:true}).fill('A103');
  await item.getByRole('button',{name:'Alternative anbieten',exact:true}).click();
  await expect(item.getByText('Alternative · noch nicht bestätigt',{exact:true})).toBeVisible();
  await page.goto(`/events/${id}`);
  await expect(page.getByText('Alternative · noch nicht bestätigt',{exact:true})).toBeVisible();
  await expect(page.getByText('A103',{exact:false})).toBeVisible();
  const visitor=await browser.newContext({viewport:{width:390,height:844}});
  try {
    const publicPage=await visitor.newPage();await publicPage.goto(`/events/${id}`);
    await expect(publicPage.getByText('Alternative · noch nicht bestätigt',{exact:true})).toBeVisible();
    await expect(publicPage.locator('main')).not.toContainText('A103');
    await page.getByRole('button',{name:'Vorgeschlagenen Termin übernehmen',exact:true}).click();
    await expect(page.getByText('17:00',{exact:false}).first()).toBeVisible();
    await expect(page.getByText('Der vorgeschlagene Termin ist übernommen. Ops bestätigt noch die Raumzusage.',{exact:true})).toBeVisible();
    await page.goto('/ops/rooms');
    await item.getByLabel('Die Bedingungen sind mit Owner und Schule vereinbart.',{exact:true}).check();
    await item.getByRole('button',{name:'Endgültig bestätigen',exact:true}).click();
    await expect(item.getByText('Raum bestätigt',{exact:true})).toBeVisible();
    await expect(item.getByRole('button',{name:'Endgültig bestätigen',exact:true})).toHaveCount(0);
    await publicPage.reload();await publicPage.getByRole('button',{name:'English'}).click();
    await expect(publicPage.getByText('Room confirmed',{exact:true})).toBeVisible();
    await expect(publicPage.locator('main')).not.toContainText('A103');
    expect(await publicPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  } finally {await visitor.close();}
});
