import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
const databaseUrl = process.env.TEST_DATABASE_URL ?? 'postgres://lab:lab_local@127.0.0.1:55433/lab_test';
if (!new URL(databaseUrl).pathname.endsWith('_test')) throw new Error('Dedicated test database required');
const pool = new Pool({ connectionString: databaseUrl });
test.beforeAll(async () => { await migrate(drizzle(pool), { migrationsFolder: './database/migrations' }); });
test.beforeEach(async () => { await pool.query('DELETE FROM activities'); await pool.query('DELETE FROM ideas'); await pool.query('DELETE FROM rate_limits'); });
test.afterAll(async () => { await pool.end(); });
test('Owner creates a Task; Member takes, releases and completes it without joining', async ({ page, browser, request }) => {
  const email = `project-${randomUUID()}@gso.schule.koeln`;
  await page.goto('/login');
  await page.getByLabel('Name', { exact: true }).fill('Private owner');
  await page.getByLabel('Schul-E-Mail').fill(email);
  await page.getByRole('button', { name: 'Login-Link senden' }).click();
  await expect(page.getByRole('status')).toContainText('Postfach');
  const box = await request.get(`http://127.0.0.1:8025/api/v1/search?query=${encodeURIComponent(`to:${email}`)}`).then(r => r.json());
  const mail = await request.get(`http://127.0.0.1:8025/api/v1/message/${box.messages[0].ID}`).then(r => r.json());
  await page.goto(mail.Text.match(/https?:\/\/\S+/)[0]);
  const response=await page.request.post('/api/projects',{headers:{origin:'http://127.0.0.1:5173'},data:{title:'Task project',description:'Together',goal:'Build'}});
  const id=(await response.json()).project.id;await page.goto(`/projects/${id}`);
  await page.getByText('Aufgabe erstellen',{exact:true}).click();
  await page.getByLabel('Aufgabentitel',{exact:true}).fill('Monitoring einrichten');
  await page.getByLabel('Aufgabenbeschreibung',{exact:true}).fill('Dashboard vorbereiten');
  await page.getByRole('button',{name:'Aufgabe speichern',exact:true}).click();
  const task=page.getByRole('article').filter({has:page.getByRole('heading',{name:'Monitoring einrichten',exact:true})}).last();
  await task.getByRole('button',{name:'Aufgabe übernehmen',exact:true}).click();
  await expect(task.getByText('In Arbeit',{exact:true})).toBeVisible();
  await expect(page.getByText('0 im Team',{exact:true})).toBeVisible();
  await task.getByRole('button',{name:'Freigeben',exact:true}).click();
  await expect(task.getByText('Offen',{exact:true})).toBeVisible();
  await task.getByRole('button',{name:'Aufgabe übernehmen',exact:true}).click();
  await page.getByRole('button',{name:'English'}).click();
  await task.getByRole('button',{name:'Mark done',exact:true}).click();
  await expect(task.getByText('Done',{exact:true})).toBeVisible();
  await expect(task.getByText('Private owner',{exact:true})).toBeVisible();
  await expect(task.getByRole('button',{name:'Release',exact:true})).toHaveCount(0);
  const visitor=await browser.newContext({viewport:{width:390,height:844}});
  try{const publicPage=await visitor.newPage();await publicPage.goto(`/projects/${id}`);
   await expect(publicPage.getByRole('heading',{name:'Monitoring einrichten',exact:true})).toBeVisible();
   await expect(publicPage.locator('main')).not.toContainText('Private owner');
   await expect(publicPage.getByRole('button',{name:'Aufgabe übernehmen',exact:true})).toHaveCount(0);
   expect(await publicPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  }finally{await visitor.close();}
});
