import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { z } from 'zod';
import type { Language } from '../i18n';

const responseSchema = z.object({ user: z.object({ id: z.string(), name: z.string() }), activities: z.array(z.object({ id: z.number(), title: z.string(), status: z.enum(['PLANNING', 'ACTIVE']) })) });
const copy = {
  de: { back: 'Ops-Team', title: 'Profil über Ops entfernen', intro: 'Personenbezogene Daten werden anonymisiert. Ergebnisse, Aufgaben und Verantwortungen bleiben als Geschichte erhalten.', owned: 'Aktive Verantwortungen', none: 'Keine aktiven Verantwortungen.', cancel: 'Diese Activities beim Entfernen abbrechen', submit: 'Profil entfernen', saving: 'Wird entfernt …', done: 'Profil wurde entfernt. Die alte Sitzung ist jetzt ungültig.', error: 'Das hat nicht geklappt. Bitte Liste neu laden.', denied: 'Dieser Bereich ist nur für Ops zugänglich.', signIn: 'Anmelden', note: 'Eine Activity ohne Nachfolger wird nur mit deiner ausdrücklichen Auswahl abgebrochen.' },
  en: { back: 'Ops team', title: 'Remove profile through Ops', intro: 'Personal data is anonymized. Results, tasks and responsibilities remain as community history.', owned: 'Active responsibilities', none: 'No active responsibilities.', cancel: 'Cancel these Activities during removal', submit: 'Remove profile', saving: 'Removing …', done: 'Profile removed. The old session is no longer valid.', error: 'Something went wrong. Reload the list.', denied: 'This area is only available to Ops.', signIn: 'Sign in', note: 'An Activity without a successor is cancelled only when you explicitly select it.' },
};
export function ProfileDeletionPage({ language }: { language: Language }) {
  const t = copy[language]; const { id = '' } = useParams(); const [data, setData] = useState<z.infer<typeof responseSchema> | null>(null); const [selected, setSelected] = useState<number[]>([]); const [state, setState] = useState<'loading' | 'ready' | 'denied' | 'error' | 'done'>('loading'); const [busy, setBusy] = useState(false);
  useEffect(() => { void fetch(`/api/ops/users/${encodeURIComponent(id)}/profile-deletion`).then(async response => { if (response.status === 401) { setState('denied'); return; } if (response.status === 403) { setState('denied'); return; } if (!response.ok) throw new Error(); setData(responseSchema.parse(await response.json())); setState('ready'); }).catch(() => setState('error')); }, [id]);
  async function remove() { setBusy(true); try { const response = await fetch(`/api/ops/users/${encodeURIComponent(id)}/profile-deletion`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ cancelActivityIds: selected }) }); if (!response.ok) throw new Error(); setState('done'); } catch { setState('error'); } finally { setBusy(false); } }
  if (state === 'denied') return <section className="season-page"><p role="alert">{t.denied}</p><Link className="text-link" to="/login">{t.signIn}</Link></section>;
  if (state === 'done') return <section className="season-page"><Link className="text-link" to="/ops">← {t.back}</Link><h1>{t.submit}</h1><p role="status">{t.done}</p></section>;
  return <section className="season-page"><Link className="text-link" to="/ops">← {t.back}</Link>{state === 'loading' && <p role="status">…</p>}{state === 'error' && <p role="alert">{t.error}</p>}{data && <><h1>{t.title}</h1><p className="season-description">{data.user.name}<br />{t.intro}</p><h2>{t.owned}</h2><p className="ops-note">{t.note}</p>{data.activities.length ? <div className="deletion-activities">{data.activities.map(activity => <label key={activity.id}><input type="checkbox" checked={selected.includes(activity.id)} onChange={event => setSelected(current => event.target.checked ? [...current, activity.id] : current.filter(value => value !== activity.id))} /> <span>{activity.title}</span><small>{activity.status}</small></label>)}</div> : <p>{t.none}</p>}<button className="button-primary" disabled={busy || selected.length !== data.activities.length} onClick={() => void remove()}>{busy ? t.saving : t.submit}</button></>}</section>;
}
