export const projectCopy = {
  de: {
    nav: 'Projekte', title: 'Gemeinsam etwas bauen.', intro: 'Von der ersten Skizze zum funktionierenden Projekt.', create: 'Projekt erstellen', edit: 'Projekt bearbeiten', back: 'Alle Projekte',
    newTitle: 'Dein nächstes Projekt.', ownership: 'Du übernimmst die Verantwortung für dieses Projekt. Andere können später mitmachen.',
    titleField: 'Titel', goal: 'Ziel', description: 'Beschreibung', techStack: 'Tech Stack', stackHint: 'Mit Komma trennen. Maximal 30 Einträge mit je 50 Zeichen.',
    repositoryUrl: 'Repository', repositoryHint:'Code, Dokumente und andere Dateien kannst du im Repository ablegen und hier verlinken.', documentationUrl: 'Dokumentation', materials: 'Materialien', privateInstructions: 'Interne Hinweise', discordUrl: 'Discord-Link',
    resources: 'Links und Tech Stack', membersOnly: 'Nur für Members', publicHint: 'Titel, Ziel, Beschreibung, Tech Stack und Repository-/Dokumentationslinks sind öffentlich. Anforderungen und Materialien gehören in die Beschreibung. Keine privaten Kontaktdaten eintragen.',
    privateHint: 'Interne Hinweise, Discord-Link und die Identität des Owners sehen nur angemeldete Members.',
    idea: 'Aus einer Idee (optional)', noIdea: 'Eigenständiges Projekt', source: 'Ursprüngliche Idee', ideaAction: 'Projekt daraus starten',
    save: 'Änderungen speichern', saving: 'Wird gespeichert …', cancel: 'Abbrechen', start: 'Arbeit starten', starting: 'Wird gestartet …', owner: 'Owner',
    PLANNING: 'In Vorbereitung', ACTIVE: 'In Arbeit', COMPLETED: 'Abgeschlossen', CANCELLED: 'Abgesagt',
    loading: 'Projekt wird geladen …', error: 'Das hat nicht geklappt. Bitte versuche es erneut.', invalid: 'Prüfe die Pflichtfelder und verwende vollständige http(s)-Links ohne Zugangsdaten.', retry: 'Erneut versuchen', missing: 'Dieses Projekt wurde nicht gefunden.',
    empty: 'Platz für das erste Projekt.', emptyBody: 'Starte etwas, das du gemeinsam mit anderen bauen möchtest.',
    login: 'Melde dich an, um ein Projekt zu erstellen.', signIn: 'Anmelden', forbidden: 'Nur Owner und Ops können dieses Projekt bearbeiten.', session: 'Deine Sitzung ist abgelaufen. Melde dich erneut an; dein Text bleibt hier stehen.', privateLogin: 'Melde dich an, um Owner und interne Informationen zu sehen.',
  },
  en: {
    nav: 'Projects', title: 'Build something together.', intro: 'From the first sketch to a working project.', create: 'Create project', edit: 'Edit project', back: 'All projects',
    newTitle: 'Your next project.', ownership: 'You take responsibility for this project. Others will be able to join later.',
    titleField: 'Title', goal: 'Goal', description: 'Description', techStack: 'Tech stack', stackHint: 'Separate with commas. Up to 30 entries, 50 characters each.',
    repositoryUrl: 'Repository', repositoryHint:'Keep code, documents and other files in the repository and link it here.', documentationUrl: 'Documentation', materials: 'Materials', privateInstructions: 'Internal instructions', discordUrl: 'Discord link',
    resources: 'Links and tech stack', membersOnly: 'Members only', publicHint: 'Title, goal, description, tech stack and repository/documentation links are public. Put requirements and materials in the description. Do not include private contact details.',
    privateHint: 'Internal instructions, Discord link and the owner’s identity are visible only to signed-in Members.',
    idea: 'Based on an idea (optional)', noIdea: 'Independent project', source: 'Original idea', ideaAction: 'Start a project from this',
    save: 'Save changes', saving: 'Saving …', cancel: 'Cancel', start: 'Start work', starting: 'Starting …', owner: 'Owner',
    PLANNING: 'Preparing', ACTIVE: 'In progress', COMPLETED: 'Completed', CANCELLED: 'Cancelled',
    loading: 'Loading project …', error: 'Something went wrong. Please try again.', invalid: 'Check the required fields and use complete http(s) links without credentials.', retry: 'Try again', missing: 'This project could not be found.',
    empty: 'Room for the first project.', emptyBody: 'Start something you would like to build with others.',
    login: 'Sign in to create a project.', signIn: 'Sign in', forbidden: 'Only the owner and Ops can edit this project.', session: 'Your session expired. Sign in again; your text will stay here.', privateLogin: 'Sign in to see the owner and internal information.',
  },
};
