import {useEffect,useId,useState,type FormEvent} from 'react';
import {Link,useParams} from 'react-router-dom';
import {z} from 'zod';
import type {Language} from '../i18n';
import {useResource} from '../shared/use-resource';
import {copy,listSchema,detailSchema,activitySchema,ActivityList,LoadState,dates,type Season} from './shared';
const recentSchema=z.object({activities:z.array(activitySchema)});
export function RecentActivities({language,onLoadingChange}:{language:Language;onLoadingChange:(loading:boolean)=>void}){const t=copy[language];const resource=useResource('/api/activities/recent',recentSchema);useEffect(()=>{onLoadingChange(resource.loading);},[resource.loading,onLoadingChange]);return <section className="recent-activities"><p className="eyebrow">{t.recent}</p>{resource.data?<ActivityList activities={resource.data.activities} language={language}/>:<LoadState {...resource} language={language}/>}</section>;}
export function SeasonContents({id,language}:{id:number;language:Language}){const resource=useResource(`/api/seasons/${id}`,detailSchema);return resource.data?<ActivityList activities={resource.data.activities} language={language}/>:<LoadState {...resource} language={language}/>;}
export function SeasonsPage({language}:{language:Language}){const t=copy[language];const resource=useResource('/api/seasons',listSchema);return <section className="ideas-page"><h1>{t.all}</h1>{!resource.data?<LoadState {...resource} language={language}/>:!resource.data.seasons.length?<p>{t.noSeasons}</p>:<ul className="idea-list">{resource.data.seasons.map(s=><li key={s.id}><Link to={`/seasons/${s.id}`}><div><span className="status">{t[s.status]}</span><h2>Season {s.number} · {s.title}</h2><p>{dates(s,language)}</p></div><span aria-hidden="true">↗</span></Link></li>)}</ul>}</section>;}
export function SeasonPage({language}:{language:Language}){const {id}=useParams();const t=copy[language];const resource=useResource(`/api/seasons/${encodeURIComponent(id??'')}`,detailSchema);const s=resource.data?.season;return <section className="ideas-page"><Link className="text-link" to="/seasons">← {t.all}</Link>{s?<><p className="status">Season {s.number} · {t[s.status]}</p><h1>{s.title}</h1><p>{dates(s,language)}</p><p className="idea-description">{s.description}</p><ActivityList activities={resource.data!.activities} language={language}/></>:<LoadState {...resource} language={language}/>}</section>;}
function SeasonForm({season,language,done}:{season?:Season;language:Language;done:()=>void}){
 const t=copy[language];const label=useId();const [busy,setBusy]=useState(false);const [error,setError]=useState<'error'|'invalid'|'conflict'|'denied'|null>(null);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);setError(null);try{
  const response=await fetch(season?`/api/ops/seasons/${season.id}`:'/api/ops/seasons',{method:season?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({number:Number(form.get('number')),title:form.get('title'),description:form.get('description'),startsOn:form.get('startsOn'),endsOn:form.get('endsOn'),status:form.get('status')}),signal:AbortSignal.timeout(10000)});
  if(!response.ok){setError(response.status===409?'conflict':response.status===400?'invalid':[401,403].includes(response.status)?'denied':'error');return;}done();
 }catch{setError('error');}finally{setBusy(false);}}
 return <form className="account-form idea-form" aria-label={season?t.edit:t.create} onSubmit={submit} aria-busy={busy}>
  <label>{t.number}<input name="number" type="number" min={0} max={2147483647} required defaultValue={season?.number??0}/></label><label>{t.title}<input name="title" required maxLength={120} defaultValue={season?.title}/></label>
  <label><span id={`${label}-description`}>{t.description}</span><textarea name="description" aria-labelledby={`${label}-description`} rows={3} maxLength={5000} defaultValue={season?.description}/></label>
  <div className="event-form-grid"><label>{t.starts}<input name="startsOn" type="date" required defaultValue={season?.startsOn}/></label><label>{t.ends}<input name="endsOn" type="date" required defaultValue={season?.endsOn}/></label></div>
  <label><span id={`${label}-status`}>{t.status}</span><select name="status" aria-labelledby={`${label}-status`} defaultValue={season?.status??'DRAFT'}>{(['DRAFT','UPCOMING','ACTIVE','FINISHED','ARCHIVED'] as const).map(status=><option key={status} value={status}>{t[status]}</option>)}</select></label>
  {error&&<p role="alert" className="form-error">{t[error]}</p>}<button className="button-primary" disabled={busy}>{busy?t.saving:t.save}</button>
 </form>;
}
export function OpsSeasonsPage({language}:{language:Language}){const t=copy[language];const resource=useResource('/api/ops/seasons',listSchema);return <section className="ideas-page"><Link className="text-link" to="/ops">← {t.back}</Link><h1>{t.manage}</h1>{!resource.data?<LoadState {...resource} language={language}/>:<><details className="project-form-section"><summary>{t.create}</summary><SeasonForm language={language} done={resource.retry}/></details>{!resource.data.seasons.length?<p>{t.noOpsSeasons}</p>:resource.data.seasons.map(season=><article key={season.id} className="season-admin-item"><span className="status">{t[season.status]}</span><h2>Season {season.number} · {season.title}</h2><p>{dates(season,language)}</p>{season.status!=='DRAFT'&&<Link className="text-link" to={`/seasons/${season.id}`}>Season {season.number} ↗</Link>}<details className="project-form-section"><summary>{t.edit}</summary><SeasonForm season={season} language={language} done={resource.retry}/></details></article>)}</>}</section>;}
