import {Link} from 'react-router-dom';
import {z} from 'zod';
import type {Language} from '../i18n';
export const seasonSchema=z.object({id:z.number(),number:z.number(),title:z.string(),description:z.string(),startsOn:z.string(),endsOn:z.string(),status:z.enum(['DRAFT','UPCOMING','ACTIVE','FINISHED','ARCHIVED'])});
export const listSchema=z.object({seasons:z.array(seasonSchema)});
export type Season=z.infer<typeof seasonSchema>;
export const activitySchema=z.object({id:z.number(),type:z.enum(['EVENT','PROJECT']),title:z.string(),description:z.string(),status:z.enum(['PLANNING','ACTIVE','COMPLETED','CANCELLED'])});
export const detailSchema=z.object({season:seasonSchema,activities:z.array(activitySchema)});
export const copy={
 de:{all:'Alle Seasons',manage:'Seasons verwalten',create:'Season erstellen',edit:'Season bearbeiten',save:'Season speichern',number:'Nummer',title:'Titel',description:'Beschreibung',starts:'Beginn',ends:'Ende',status:'Status',DRAFT:'Entwurf',UPCOMING:'Demnächst',ACTIVE:'Aktiv',FINISHED:'Beendet',ARCHIVED:'Archiviert',PLANNING:'In Vorbereitung',COMPLETED:'Abgeschlossen',CANCELLED:'Abgesagt',events:'Events',projects:'Projekte',recent:'Neu im Lab',empty:'Noch keine Aktivitäten.',noSeasons:'Noch keine veröffentlichten Seasons.',noOpsSeasons:'Noch keine Seasons. Erstelle die erste.',loading:'Wird geladen …',error:'Das hat nicht geklappt. Bitte erneut versuchen.',invalid:'Prüfe Nummer, Titel und Zeitraum.',conflict:'Die Nummer ist bereits vergeben oder eine andere Season ist aktiv. Beende sie zuerst.',denied:'Dieser Bereich ist nur für Ops zugänglich.',missing:'Season nicht gefunden.',retry:'Neu laden',saving:'Wird gespeichert …',login:'Anmelden',back:'Ops-Team'},
 en:{all:'All seasons',manage:'Manage seasons',create:'Create season',edit:'Edit season',save:'Save season',number:'Number',title:'Title',description:'Description',starts:'Starts',ends:'Ends',status:'Status',DRAFT:'Draft',UPCOMING:'Upcoming',ACTIVE:'Active',FINISHED:'Finished',ARCHIVED:'Archived',PLANNING:'Planning',COMPLETED:'Completed',CANCELLED:'Cancelled',events:'Events',projects:'Projects',recent:'New in the Lab',empty:'No activities yet.',noSeasons:'No published seasons yet.',noOpsSeasons:'No seasons yet. Create the first one.',loading:'Loading …',error:'Something went wrong. Please try again.',invalid:'Check the number, title and dates.',conflict:'The number is already used or another season is active. Finish it first.',denied:'This area is only available to Ops.',missing:'Season not found.',retry:'Reload',saving:'Saving …',login:'Sign in',back:'Ops team'},
};
export function LoadState({loading,status,retry,language}:{loading:boolean;status:number;retry:()=>void;language:Language}){
 const t=copy[language];return loading?<p role="status">{t.loading}</p>:[401,403].includes(status)?<p role="alert">{t.denied} <Link to="/login">{t.login}</Link></p>:status===404?<p role="alert">{t.missing}</p>:<p role="alert">{t.error} <button className="text-link" onClick={retry}>{t.retry}</button></p>;
}
export function ActivityList({activities,language,headingLevel=2}:{activities:z.infer<typeof activitySchema>[];language:Language;headingLevel?:2|3}){
 const t=copy[language];return <>{(['EVENT','PROJECT'] as const).map(type=>{const items=activities.filter(a=>a.type===type);const title=type==='EVENT'?t.events:t.projects;return <section key={type} className="season-activities">{headingLevel===3?<h3>{title}</h3>:<h2>{title}</h2>}{!items.length?<p className="ideas-note">{t.empty}</p>:<ul className="idea-list">{items.map(item=><li key={item.id}><Link to={`/${type==='EVENT'?'events':'projects'}/${item.id}`}><div><span className="status">{t[item.status]}</span>{headingLevel===3?<h4>{item.title}</h4>:<h3>{item.title}</h3>}<p className="idea-preview">{item.description}</p></div><span aria-hidden="true">↗</span></Link></li>)}</ul>}</section>;})}</>;
}
export function dates(season:Season,language:Language){const f=new Intl.DateTimeFormat(language==='de'?'de-DE':'en-GB',{dateStyle:'medium',timeZone:'UTC'});return `${f.format(new Date(`${season.startsOn}T00:00:00Z`))} – ${f.format(new Date(`${season.endsOn}T00:00:00Z`))}`;}
